package Thing
{
    public class CBambo extends CPeepPlayer
    {
         
        
        public function CBambo(param1:Object = null)
        {
            super(param1,SheetBambo);
            mUpgrades = mDefaultUpgrades;
            InitWeapons([CPistol,CShotgun,CBarrels,CBarricades,CWTurret_MG,CMinigun,CGrenades,CRocketLauncher,CWTurret_Mortor,CAirstrike]);
        }
        
        override public function get mDefaultUpgrades() : Array
        {
            var _loc1_:* = null;
            return [{
                "mIndex":4,
                "mClassID":CPistol,
                "mUpgrade":1
            },{
                "mIndex":5,
                "mClassID":CShotgun,
                "mUpgrade":0
            },{
                "mIndex":11,
                "mClassID":CPistol,
                "mUpgrade":2
            },{
                "mIndex":17,
                "mClassID":CShotgun,
                "mUpgrade":1
            },{
                "mIndex":18,
                "mClassID":CPistol,
                "mUpgrade":3
            },{
                "mIndex":20,
                "mClassID":CBarrels,
                "mUpgrade":0
            },{
                "mIndex":32,
                "mClassID":CShotgun,
                "mUpgrade":2
            },{
                "mIndex":32,
                "mClassID":CBarrels,
                "mUpgrade":1
            },{
                "mIndex":40,
                "mClassID":CBarricades,
                "mUpgrade":0
            },{
                "mIndex":47,
                "mClassID":CShotgun,
                "mUpgrade":3
            },{
                "mIndex":47,
                "mClassID":CBarrels,
                "mUpgrade":2
            },{
                "mIndex":52,
                "mClassID":CBarricades,
                "mUpgrade":1
            },{
                "mIndex":60,
                "mClassID":CWTurret_MG,
                "mUpgrade":0
            },{
                "mIndex":62,
                "mClassID":CShotgun,
                "mUpgrade":4
            },{
                "mIndex":62,
                "mClassID":CBarrels,
                "mUpgrade":3
            },{
                "mIndex":67,
                "mClassID":CBarricades,
                "mUpgrade":2
            },{
                "mIndex":77,
                "mClassID":CShotgun,
                "mUpgrade":5
            },{
                "mIndex":77,
                "mClassID":CBarrels,
                "mUpgrade":4
            },{
                "mIndex":80,
                "mClassID":CMinigun,
                "mUpgrade":0
            },{
                "mIndex":82,
                "mClassID":CBarricades,
                "mUpgrade":3
            },{
                "mIndex":82,
                "mClassID":CWTurret_MG,
                "mUpgrade":1
            },{
                "mIndex":90,
                "mClassID":CGrenades,
                "mUpgrade":0
            },{
                "mIndex":92,
                "mClassID":CShotgun,
                "mUpgrade":6
            },{
                "mIndex":97,
                "mClassID":CBarricades,
                "mUpgrade":4
            },{
                "mIndex":100,
                "mClassID":CRocketLauncher,
                "mUpgrade":0
            },{
                "mIndex":102,
                "mClassID":CMinigun,
                "mUpgrade":1
            },{
                "mIndex":102,
                "mClassID":CGrenades,
                "mUpgrade":1
            },{
                "mIndex":107,
                "mClassID":CShotgun,
                "mUpgrade":7
            },{
                "mIndex":117,
                "mClassID":CWTurret_MG,
                "mUpgrade":2
            },{
                "mIndex":117,
                "mClassID":CRocketLauncher,
                "mUpgrade":1
            },{
                "mIndex":122,
                "mClassID":CShotgun,
                "mUpgrade":8
            },{
                "mIndex":125,
                "mClassID":CWTurret_Mortor,
                "mUpgrade":0
            },{
                "mIndex":127,
                "mClassID":CGrenades,
                "mUpgrade":2
            },{
                "mIndex":137,
                "mClassID":CMinigun,
                "mUpgrade":2
            },{
                "mIndex":150,
                "mClassID":CWTurret_Mortor,
                "mUpgrade":1
            },{
                "mIndex":150,
                "mClassID":CAirstrike,
                "mUpgrade":0
            },{
                "mIndex":152,
                "mClassID":CWTurret_MG,
                "mUpgrade":3
            },{
                "mIndex":152,
                "mClassID":CGrenades,
                "mUpgrade":3
            },{
                "mIndex":152,
                "mClassID":CRocketLauncher,
                "mUpgrade":2
            },{
                "mIndex":172,
                "mClassID":CMinigun,
                "mUpgrade":3
            },{
                "mIndex":175,
                "mClassID":CAirstrike,
                "mUpgrade":1
            },{
                "mIndex":177,
                "mClassID":CGrenades,
                "mUpgrade":4
            },{
                "mIndex":185,
                "mClassID":CWTurret_Mortor,
                "mUpgrade":2
            },{
                "mIndex":187,
                "mClassID":CWTurret_MG,
                "mUpgrade":4
            },{
                "mIndex":187,
                "mClassID":CRocketLauncher,
                "mUpgrade":3
            },{
                "mIndex":207,
                "mClassID":CMinigun,
                "mUpgrade":4
            },{
                "mIndex":220,
                "mClassID":CWTurret_Mortor,
                "mUpgrade":3
            },{
                "mIndex":222,
                "mClassID":CWTurret_MG,
                "mUpgrade":5
            },{
                "mIndex":222,
                "mClassID":CRocketLauncher,
                "mUpgrade":4
            },{
                "mIndex":225,
                "mClassID":CAirstrike,
                "mUpgrade":2
            },{
                "mIndex":242,
                "mClassID":CMinigun,
                "mUpgrade":5
            },{
                "mIndex":255,
                "mClassID":CWTurret_Mortor,
                "mUpgrade":4
            },{
                "mIndex":300,
                "mClassID":CRocketLauncher,
                "mUpgrade":5
            },{
                "mIndex":400,
                "mClassID":CRocketLauncher,
                "mUpgrade":6
            },{
                "mIndex":500,
                "mClassID":CAirstrike,
                "mUpgrade":3
            }];
        }
        
        override public function get _CLASSID_() : String
        {
            return "CBambo";
        }
    }
}
